# Generated by Django 4.2.16 on 2024-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
