# Generated by Django 4.2.16 on 2024-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_telegramuser_last_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt', models.IntegerField(blank=True)),
                ('coms', models.IntegerField(blank=True)),
            ],
        ),
    ]
