# Generated by Django 4.2.16 on 2024-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_currentcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltc_sum', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('req', models.TextField()),
            ],
        ),
    ]
