# Generated by Django 4.2.16 on 2024-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcourse',
            old_name='coms',
            new_name='coms_10_20',
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='coms_20_30',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='coms_30',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='coms_5',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='coms_5_10',
            field=models.IntegerField(blank=True, default=1.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='kgs_sum',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='req',
            field=models.TextField(blank=True, null=True),
        ),
    ]
