# Generated by Django 4.2.16 on 2024-10-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_rename_coms_currentcourse_coms_10_20_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
