# Generated by Django 4.2.16 on 2024-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_order_coms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcourse',
            old_name='coms_30',
            new_name='coms_30_70',
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='coms_70_120',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
