# Generated by Django 4.2.16 on 2024-10-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0009_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum_for_op',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
