# Generated by Django 4.2.16 on 2024-10-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0010_order_sum_for_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLtcReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
