# Generated by Django 4.2.16 on 2024-11-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0011_mainltcreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='operator_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
